apiVersion: apps/v1
kind: Deployment
metadata:
  name: breakout-api
  labels:
    app: breakout-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: breakout-api
  template:
    metadata:
      labels:
        app: breakout-api
    spec:
      containers:
      - name: api
        image: breakout-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: breakout-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: breakout-config
              key: db_port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: breakout-secrets
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: breakout-secrets
              key: db_password
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: breakout-config
              key: db_database
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: breakout-secrets
              key: jwt_secret
        - name: SOLANA_NETWORK
          valueFrom:
            configMapKeyRef:
              name: breakout-config
              key: solana_network
        - name: SOLANA_RPC_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: breakout-config
              key: solana_rpc_endpoint
        - name: ESCROW_PROGRAM_ID
          valueFrom:
            configMapKeyRef:
              name: breakout-config
              key: escrow_program_id
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: breakout-api-service
spec:
  selector:
    app: breakout-api
  ports:
  - port: 80
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: breakout-config
data:
  db_host: "postgres-service"
  db_port: "5432"
  db_database: "breakout"
  solana_network: "devnet"
  solana_rpc_endpoint: "https://api.devnet.solana.com"
  escrow_program_id: "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
---
apiVersion: v1
kind: Secret
metadata:
  name: breakout-secrets
type: Opaque
data:
  db_username: cG9zdGdyZXM=  # postgres (base64 encoded)
  db_password: cG9zdGdyZXM=  # postgres (base64 encoded)
  jwt_secret: Y2hhbmdlLXRoaXMtc2VjcmV0LWluLXByb2R1Y3Rpb24=  # change-this-secret-in-production (base64 encoded)
